//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gift()
        {
            this.MemberCardLevels = new HashSet<MemberCardLevel>();
        }
    
        public string ID { get; set; }
        public string GiftLevelName { get; set; }
        public string GiftTypeID { get; set; }
        public Nullable<double> RewardRate { get; set; }
        public Nullable<double> PointPlus { get; set; }
        public string SpecialMemoryID { get; set; }
        public string PersonalGiftID { get; set; }
    
        public virtual PersonalGift PersonalGift { get; set; }
        public virtual SpecialMemory SpecialMemory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberCardLevel> MemberCardLevels { get; set; }
    }
}
