//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveCard
    {
        public int ID { get; set; }
        public string CardID { get; set; }
        public string ReaderID { get; set; }
        public Nullable<System.DateTime> ScanAt { get; set; }
    }
}
