//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCardLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberCardLevel()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public string LevelID { get; set; }
        public string CardLevelID { get; set; }
        public string GiftLevelID { get; set; }
        public Nullable<bool> VIP { get; set; }
        public string VIPGiftID { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> Points { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual CardLevel CardLevel { get; set; }
        public virtual Gift Gift { get; set; }
        public virtual VIPGift VIPGift { get; set; }
    }
}
