//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCard
    {
        public string AccountID { get; set; }
        public int MemberCardLevelID { get; set; }
        public Nullable<double> Points { get; set; }
        public Nullable<double> Balance { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual MemberCardLevel MemberCardLevel { get; set; }
    }
}
