//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCardChargeRecord
    {
        public int RecordID { get; set; }
        public string AccountID { get; set; }
        public string MemberCardID { get; set; }
        public Nullable<double> Money { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> TypePay { get; set; }
        public string Paycode { get; set; }
        public string RecordType { get; set; }
        public string Cashier { get; set; }
        public string PromotionID { get; set; }
        public string PromotionDes { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual MemberCard MemberCard { get; set; }
        public virtual PayType PayType { get; set; }
    }
}
